services:
  python-backend:
    build: ./python-backend
    tty: true
    ports:
      - "5002:5001"
    environment:
      - FLASK_ENV=docker

  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    restart: always
    ports:
      - "9002:9000"
      - "9003:9001"
    volumes:
      - ./minio_data:/data
    environment:
      - MINIO_ROOT_USER=minio_admin
      - MINIO_ROOT_PASSWORD=minio_pass
    command: server /data --console-address ":9001" --compat

  minio-setup:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 10;
        /usr/bin/mc alias set myminio http://minio:9000 minio_admin minio_pass;
        /usr/bin/mc mb myminio/plot-figure || true;
        /usr/bin/mc anonymous set download myminio/plot-figure;
        while true; do sleep 3600; done;
      "
