services:
  react-frontend:
    build: ./react-frontend
    tty: true
    ports:
      - "4174:4173"

  python-backend:
    build: ./python-backend
    tty: true
    ports:
      - "5002:5001"
    volumes:
      - ./python-backend/static:/usr/src/server/static
    environment:
      - FLASK_ENV=docker
